### PR TITLE
Job::OwnData add self protect

### PR DESCRIPTION
**Pull request by changshuang**

### CODE REVIEW

**Comment by ffulin** [comment]
Is there a need for this change? Set a job to own the data it already owns seems like it would be a bug and should not be handled gracefully.

**Comment by changshuang** [comment]
This is just a prevention of free self. E.g: #353 . If user pass its own data to function "owndata", the function will free data firstly, then the data is invalid. But next it will be assigned to m_Data as normal data. It will lead crash sometimes because of using the invalid data in memroy.

Of cause, this can be avoided by user's judgement. But as a offical c++ code, i thind it is necessary to add a self protect. That is just my opinion.

**Comment by ffulin** [comment]
I've reworked this code a little bit in order to expose the memory limit via Settings(). As part of this change (https://github.com/fastbuild/fastbuild/commit/53560f6ca39a88e2ad79b121cf551589a5fcd142) I've made redundant calls to to OwnsData be caught by an ASSERT. This change will be part of the next release (v0.95). I'll leave this pull request open to track that.

**Comment by ffulin** [comment]
v0.95 has now been released and the source includes protection for misuse of this API. Thanks for reporting this issue!

**Pull request closed without merging**
