### PR TITLE
New function SLN()

### PR DESCRIPTION
**Pull request by poppolopoppo**
SLN() generates a Visual Studio Solution File (*.sln).
* The format used is `Microsoft Visual Studio Solution File, Format Version 12.00` (>= Visual 2012). Support for earlier formats (like Visual 2010) could be done in the future but is not available yet.
* SLNNode uses VCXProjectNodes to retrieve each referenced project guid and path. _.SolutionProjects_ can follow aliases to find a VCXProjectNode target.
* _.SolutionConfigs_ must match the VSProjectConfigs of each referenced VCXProjectNodes. If _.SolutionConfigs_ is not specified, the same default configuration than VCXProject() is assumed.
* _.SolutionFolders_ can be used to group projects in solution folders in Visual Studio. Each folder in the path will be automatically created if not defined by the user (`mkdir -p` like).
* SLNGenerator generates sln files matching Visual Studio ordering and naming.

Ex:
````
SLN( alias )
{
	.SolutionOutput     				; Filename of solution file
	.SolutionProjects   				; List of VCXProjects previously defined

	.SolutionConfigs    				; (optional) project configurations (see VCXProject)
	.SolutionFolders 					; (optional) List of solution folders (see below)

	.SolutionVisualStudioVersion        ; (optional) Default is "14.0.22823.1"
	.SolutionMinimumVisualStudioVersion ; (optional) Default is "10.0.40219.1"
}
````
````
// .SolutionFolders - structs in the following format
//---------------------------------------------------
.SolutionFolder =
[
	.Path          						; Absolute path of the folder (Ex: Folder\SubFolder)
	.ProjectNames  						; List of contained project names
]
````

### CODE REVIEW

**Comment by ffulin** [comment]
Hello

This is very nice - thankyou :+1: . I took a look through the changes and they all look good.

A couple of questions:
 - Which projects are built when you do a "solution build"?  Because FASTBuild manages the dependencies (and not MSBuild) you typically need to have just one project "enabled" to act as as the "master" project (to avoid havgin multiple instances of FASTBuild spawned). I didn't see anything like that, or how you would specify which project is the master project.
 - How do you specify which projects go into which solution folders?

**Comment by poppolopoppo** [comment]
* Mmh, I did not address this issue... I'll add an optional _.SolutionBuildProject_ field, only adding the _.Build.0_ line in the _ProjectConfigurationPlatforms_ section for this project should do the trick.
* The solution folders are used like this :
````
SLN( 'sln' )
{
    .SolutionOutput = 'solution.sln'
    .SolutionProjects = { 'a-proj', 'b-proj', 'c-proj', 'd-proj' }
    .FolderCoreXXX =
    [
        .Path = 'Core/XXX'
        .ProjectNames = { 'a-proj' }
    ]
    .FolderCoreABC =
    [
        .Path = 'Core/A/B/C'
        .ProjectNames = { 'b-proj', 'c-proj' }
    ]
    .FolderCoreOtherBC =
    [
        .Path = 'Core/Other/B/C'
        .ProjectNames = { 'd-proj' }
    ]
    .SolutionFolders = { .FolderCoreXXX, .FolderCoreABC, /FolderCoreOtherBC }
}
````
This will generate the following solution folders : _Core_, _Core/XXX_, _Core/A_, _Core/A/B_, _Core/A/B/C_, _Core/Other_, _Core/Other/B_ & _Core/Other/B/C_.

Sadly, the current syntax does not allow this more elegant version :
````
SLN( 'sln' )
{
    .SolutionOutput = 'solution.sln'
    .SolutionProjects = { 'a-proj', 'b-proj', 'c-proj', 'd-proj' }
    .SolutionFolders = 
    {
        [
            .Path = 'Core/XXX'
            .ProjectNames = { 'a-proj' }
        ],
        [
            .Path = 'Core/A/B/C'
            .ProjectNames = { 'b-proj', 'c-proj' }
        ],
        [
            .Path = 'Core/Other/B/C'
            .ProjectNames = { 'd-proj' }
        ],
    }
}
````

**Comment by poppolopoppo** [comment]
I updated the branch :
* _.SolutionBuildProject_ can be used to specify the master project. If specified this will be the only project active in SolutionManager. Other projects are always disabled, but can be still built individually.
* Checks that _.SolutionBuildProject_ and each _.Projects_ from _.SolutionFolders_ are contained in _.SolutionProjects_.
* I changed _.ProjectNames_ for _.Projects_ in _.SolutionFolders_, which is more consistent with the other fields.
* I handled the case where the Node is not found when looking for a project with an error 1104.

New example :
````
SLN( 'sln' )
{
    .SolutionOutput = 'solution.sln'
    .SolutionProjects = { 'a-proj', 'b-proj', 'c-proj', 'd-proj' }
    .SolutionBuildProject = 'a-proj'
    .FolderCoreXXX =
    [
        .Path = 'Core/XXX'
        .Projects = { 'a-proj' }
    ]
    .FolderCoreABC =
    [
        .Path = 'Core/A/B/C'
        .Projects = { 'b-proj', 'c-proj' }
    ]
    .FolderCoreOtherBC =
    [
        .Path = 'Core/Other/B/C'
        .Projects = { 'd-proj' }
    ]
    .SolutionFolders = { .FolderCoreXXX, .FolderCoreABC, /FolderCoreOtherBC }
}
````

**Comment by ffulin** [comment]
Thanks for the updates and the clarifying examples.  I'll try to get this integrated soon.

**Comment by ffulin** [comment]
I've integrated this into the Perforce mainline.  This will be part of the v0.84 release.

I made a few modifications to your pull request while integrating it (which will make their way back into git when I integrate the v0.84 release):
* The name exposed to the BFF is VSSolution instead of SLN (class name remains the same)
* A few places now use AStackString<> instead of AString (AStackString<> can be passed to functions that take AString&)
* Collasped m_Tmp and m_OutputSLN together
* Removed unnecessary manual folder creation for SLNNode (it is a FileNode so the folder is created automatically already)
* Made line endings in .sln file be \r\n to be consistent with a "real" Solution

I've also updated the fbuild.bff for FASTBuild to use the new VSSolution for generating its own solution :)

Thanks again for this change! ;)

**Pull request merged**
