### PR TITLE
Non MSVC library flags are ignored

### PR DESCRIPTION
**Pull request by fran6co**
They should start with `-`

### CODE REVIEW

**Comment by ffulin** [comment]
Thanks for the fix. I think it would be better to fix the GetOtherLibsArg function instead (so that it behaves consistently). What do you think?

**Comment by fran6co** [comment]
That's probably better, I just tried to find a minimal fix for this.

**Comment by fran6co** [comment]
@ffulin do you think it's better like this?

**Comment by ffulin** [comment]
I took a look at your new version, but unfortunately that code doesn't compiler (cannot add two pointers).

I think the correct fix would be to implement a new IsStartOfLinkerArg which would be a slightly altered version of IsStartOfLinkerArg_MSVC.

IsStartOfLinkerArg would look something like this:
```C++
/*static*/ bool LinkerNode::IsStartOfLinkerArg_MSVC( const AString & token, const char * arg )
{
    ASSERT( token.IsEmpty() == false );

    // Args can start with -
    if ( token[0] != '-' )
    {
        return false;
    }

    // Length check to early out
    const size_t argLen = AString::StrLen( arg );
    if ( ( token.GetLength() - 1 ) < argLen )
    {
        return false; // token is too short
    }

    // Args are case-sensitive
    return ( AString::StrNCmp( token.Get() + 1, arg, argLen ) == 0 );
}
```
(the difference being that its case-sensitive and only checks for '-').

Then we could simply call that in the else clause of GetOtherLibsArg:
{code}
    else
    {
        if ( IsStartOfLinkerArg( *it, arg ) == false )
        {
            return false; // not our arg, not consumed
        }
    }
{code}

**Comment by fran6co** [comment]
@ffulin fixed

**Comment by ffulin** [comment]
Thanks for the fix. I've merged the pull request and the fix will be in the next release (v0.96). I went ahead and added some regression tests as well (https://github.com/fastbuild/fastbuild/commit/9e240dcbe668abf9afe1737d6e1cab3df9ac64ab).

**Pull request merged**
