### PR TITLE
Update to syntax highlighting integration (notepad++ & VS usertypes.dat)

### PR DESCRIPTION
**Pull request by lucianm**
Hello Franta,

I found some keywords to be missing and one duplicate...

Greetings,
Lucian

### CODE REVIEW

**Comment by lucianm** [comment]
I actually suspected that, but didn't bother to systematically check and add more than those I stumbled upon myself. Is your Vim list complete?

**Comment by dummyunit** [comment]
I hope it is. I generate it with the help of [this script](https://github.com/dummyunit/vim-fastbuild/blob/master/check_properties.sh) which grep entire FASTBuild source code for string literals that look like a property name and then filters the results removing ones that proven to not be a property name.

**Comment by lucianm** [comment]
Ok, I will give it a try to find the missing keywords. dummyunit, the link to your script reveale that you're using gentoo the passionate way (hosting an overlay, packaging FASTBuild as well), I like that :-). Did you consider submitting the fastbuild Ebuild to https://bugs.gentoo.org for upstream adoption?

**Comment by dummyunit** [comment]
> Did you consider submitting the fastbuild Ebuild to https://bugs.gentoo.org for upstream adoption?

As far as I remember there were still some issues with it (some tests were failing under sandbox). I will look into fixing and upstreaming it on the weekend.

**Comment by ffulin** [comment]
Thanks for the fixes. This has been integrated and will be in the next release (v0.96).

Once the work is complete to convert all the internal structures to use the reflection system (about 90% complete) I will think about a script to auto generate all the various markup files to automate this process.

**Pull request merged**
