### PR TITLE
Add support for non-recursive input paths in VCXProject and XCodeProject

### PR DESCRIPTION
**Pull request by to01z**
# Description:
This PR implements support for non-recursive .ProjectInputPaths in VCXProject and XCodeProject. The user can opt into this behavior by setting the new .ProjectInputPathsRecurse property to false.

Please provide details for the change or fix:
Motivations for this change are presented and assessed in #948.

# Checklist:

The pull request:
- [X] **Is created against the Dev branch**
- [X] **Is self-contained**
- [ ] **Compiles on Windows, OSX and Linux** ; I have only had opportunity to test Windows MSVC/ Clang
- [X] **Has accompanying tests**
- [X] **Passes existing tests**
- [X] **Keeps Windows, OSX and Linux at parity**
- [X] **Follows the code style**
- [X] **Includes documentation**

### CODE REVIEW

**Comment by ffulin** [comment]
Nice one - thanks :)

**Comment by to01z** [comment]
I will have to look at that Linux TSan fail - no sure what is going on there.

**Comment by ffulin** [comment]
The TSan failure is a false positive. I've re-run the test. I need to get to the bottom of that at some point.

**Comment by ffulin** [comment]
Thanks for the enhancement! This has been integrated and will be in the next release (v1.09)

**Pull request merged**
