### PR TITLE
Update brokerage file to use ip address instead of host name

### PR DESCRIPTION
**Pull request by Rinn**
# Description:
Updates the brokerage availability file to use IP address instead of host name, to address situations where machines are on different domains, or if a host name is unresolvable but the ip address can be directly connected to.

- Use ip address instead of host name for brokerage filename, if an ip address is not available use the host name instead as a fallback
- Added rerequesting host name and domain name, and resolving the local host name to ip address in WorkerBrokerage on a 5 minute timer. If the ip address changes the previous brokerage file will be deleted and a new one with an updated filename will be written
- Write host name, ip address, and memory threshold to brokerage file
- Write domain name and FQDN to brokerage file if the domain name is not empty

This change should resolve issues https://github.com/fastbuild/fastbuild/issues/160, https://github.com/fastbuild/fastbuild/issues/271, & probably helps https://github.com/fastbuild/fastbuild/issues/643

I'll need to update PR https://github.com/fastbuild/fastbuild/pull/767 if this is accepted first.

# Checklist:

The pull request:
- [x] **Is created against the Dev branch**
- [x] **Is self-contained**
- [x] **Compiles on Windows, OSX and Linux**
- [ ] **Has accompanying tests**
- [x] **Passes existing tests**
- [x] **Keeps Windows, OSX and Linux at parity**
- [x] **Follows the code style**
- [ ] **Includes documentation**

### CODE REVIEW

**Comment by fsfod** [comment]
I ran in to an issue where a worker wasn't connected to because the resolved ip of the broker hostname was stale but the ip in the broker name was accessible . I don't think  TCPConnectionPool::Connect loop should early exit if  a connect fails and there are still more ips from the broker name to try.

I changed the loop to this and the worker was connected to successfully. Idk if the loop should maybe some have accumulated timeout if its setup like this. 
```c
	const ConnectionInfo* conn = NULL;
	for ( const AString& value : hosts )
	{
		hostIP = Network::GetHostIPFromName( value, timeout );
		if ( hostIP == 0 )
		{
			TCPDEBUG("Failed to get address for '%s'\n", host.Get());
			continue;
		}

		conn = Connect( hostIP, port, timeout, userData );

		if ( conn )
		{
			return conn;
		}
	}

	return conn;
```

**Comment by Rinn** [comment]
Yeah I was considering that. It would need to keep track of which IPs were attempted so it doesn't possibly waste time if the dns resolution returns the same ip address that was provided from the broker file.

**Comment by Rinn** [comment]
Another CI build that [passed on my fork](https://travis-ci.com/github/Rinn/fastbuild/builds/176365238), might be a flaky test.

**Comment by ffulin** [comment]
Thanks for the PR. I was finally able to take some time to look it over.

I like the idea of writing the brokerage token in a way that improves connectivity, but the current change is implemented in a way that makes it a breaking change (which you obviously noted as you updated the protocol version) While some users automate the update of their workers (submitting them to source control for example) others have a more manual process, so breaking changes to the protocol can cause non-trivial inconvenience for some users and has been noted by some as a reason for them updating less frequently.

Here are a few things we can talk about to figure out how to move forward:

**Could we just write the qualified hostname OR just the IP?**

If we wrote just the qualified hostname, we could maintain backward compatibility. Similarly, just writing the IP would also be backwards compatible (as well as avoiding a hostname lookup on the client for every worker it connects to). I can see how having both might improve connectivity in some scenarios, but I think either of them alone likely solves for common connectivity problems. Since you implemented this to fix a real-world scenario, I'm curious if you have any more info on the behavior you saw that you could share?

If necessary, we could allow a new version to write two versions of the token to provide a smooth transition, though of course this would add some complexity.

**Network::GetHostName taking a + delimiter list is a bit odd**

It seems strange that a low level function (in the FASTBuild-agnostic Core libraries) is aware of the custom way the higher level FASTBuild code happens to store multiple entries in a string. I think the higher level code should do the tokenization if we retain this logic.

**The FBuildWorker UI doesn't display the correct hostname**

The FBuildWorker UI shows the local hostname. I believe a hostname change requires a reboot (at least on Windows), but assuming the domain can change does not, the UI can now be out of date. I think this can be resolved by having the WorkerWindow ask the brokerage for the hostname instead of retrieving itself.

**Comment by Rinn** [comment]
**Could we just write the qualified hostname OR just the IP?**
Yeah I'm fine with this, for my use case it would need to be the IP instead of hostname because I'm trying to work around corporate DNS issues when on VPN that has issues with resolving user pc hostnames to IP addresses. My original thoughts was to put as much into the filename as I could as a fallback, the FQDN was something I believed would help the three issues I mentioned, but IP alone will probably resolve any connection issue related to not being able to dns resolve.

Another reason I left the host name in there was because the output uses that string to display which worker is being used for a task and I figured hostname would be good to keep as it's more descriptive than IP address and it continued to prevent the need to open the file to get additional information. If that's a non-issue that I'm fine with only ip address.

**Network::GetHostName taking a + delimiter list is a bit odd**
Yeah fair point, I can move the logic, but if we switch the filename to ip only instead of + delimited this will be a non-issue.

**The FBuildWorker UI doesn't display the correct hostname**

**Comment by Rinn** [comment]
Okay I fixed the FBuildWorker UI. Let me know what you think about the filename. If changing it to IP address is what you want I can make that change (falling back to hostname if the ip address isn't available) and I'll remove the + delimited code.

**Comment by ffulin** [comment]
I think using the IP as the filename is the best way to go for now (retains compatibility, fixes your problem and saves some DNS lookups).

Since having the hostname can be useful for human inspection of the brokerage, one thing we could do is write that entry inside the brokerage file. That means in the worst case, someone can do something like a "Find in Files" to find the hostname of a misbehaving IP. Since normal builds won't need to open the file, I don't see a downside to having this additional info there.

How does that sound?

**Comment by Rinn** [comment]
Sure sounds good to me, I'll make that change.

**Comment by Rinn** [comment]
Alright, this should be done. To summarize what is now in this PR:

- Use ip address instead of host name for brokerage filename, if an ip address is not available use the host name instead as a fallback
- Write host name, ip address, and memory threshold to brokerage file
- Write domain name & FQDN to brokerage file if the domain name is not empty
- Host name, domain name, and ip address is reacquired on a timer in WorkerBrokerage to detect any changes and recreate the brokerage file if necessary.

**Comment by ffulin** [comment]
Thanks for the updated PR. This change has been integrated and will be in the next release (v1.03)

**Pull request merged**
