### PR TITLE
Alternative syntax ."Some$Var$"

### PR DESCRIPTION
**Pull request by poppolopoppo**
Variables can now be used like this :
````javascript
.Foobar = 'foo'
."Foobar" + 'bar'
Print( .Foobar ) // "foobar"
."$Foobar$" = 'barfoo'
Print( .Foobar ) // "barfoo"
````
Which allows :
````javascript
.CompilerOptions_Debug = ' -D_DEBUG'
.CompilerOptions_Release = ' -DNDEBUG'

.BuildConfigs = { 'Debug', 'Release' }

ForEach( .Config in .BuildConfigs )
{
    .CompilerOptions = ."CompilerOptions_$Config$" 
    Print( .CompilerOptions ) // " -D_DEBUG"
                              // " -DNDEBUG"
}
````
This is particularly useful when used conjointly with [optional assignment](https://github.com/fastbuild/fastbuild/pull/20) :
````javascript
.CompilerOptions_Debug = ' -D_DEBUG'
.CompilerOptions_Release = ' -DNDEBUG'
.CompilerOptions_Win32 = ' -DX86'
.CompilerOptions_Win64 = ' -DX64'
.CompilerOptions_Win32_Debug = ' -DWIN32_DEBUG'

.BuildPlatfoms = { 'Win32', 'Win64' }
.BuildConfigs = { 'Debug', 'Release' }

ForEach( .Platform in .BuildPlatforms )
ForEach( .Config in .BuildConfigs )
{
    ."CompilerOptions_$Platform$" ? ''
    ."CompilerOptions_$Config$" ? ''
    ."CompilerOptions_$Platform$_$Config$" ? ''

    .CompilerOptions = ."CompilerOptions_$Platform$"
                     + ."CompilerOptions_$Config$"
                     + ."CompilerOptions_$Platform$_$Config$"

    Print( .CompilerOptions ) // " -DX86 -D_DEBUG -DWIN32_DEBUG"
                              // " -DX86 -DNDEBUG"
                              // " -DX64 -D_DEBUG"
                              // " -DX64 -DNDEBUG"
}
````

### CODE REVIEW

**Comment by kylawl** [comment]
We've been running with this feature for months now, works great.

Thanks

**Comment by kylawl** [comment]
I hate to be a pest, but I'd love to see this in v0.88 if possible. We've been running on @poppolopoppo's fork for quite some time. This is the last feature we're relying on that prevents us from going back to mainline.

**Comment by ffulin** [comment]
I'll see what I can do.  Looks like it should be a fairly clean integration, but I'll need to author some tests.

**Comment by ffulin** [comment]
This change has been integrated into the Perforce main line and will be in the next release (v0.88). I'll leave this issue open until the new version is released.

As part of the integration I added some units tests and basic documentation for this feature.

**Comment by kylawl** [comment]
That's great. Thanks so much

/ Kyle

**Pull request merged**
