### PR TITLE
Add option "-nolocalrace"

### PR DESCRIPTION
**Pull request by belkiss**
With this, a job is either done locally or remotely and FB waits for it to finish. There is no more kill involved.

This was done to solve the issue we experienced related to kill process tree.

### CODE REVIEW

**Comment by ffulin** [comment]
This option seems like it would have been useful for debugging originally, but it seems like there's no good reason to keep it now, right?

**Comment by jspelletier** [comment]
we often still use this option internally at Ubisoft for debugging some issues. This is really a debugging option and wouldn't mind that this is put in a special experimental section in -help(same thing applies to --debugpreprocessor)

**Comment by ffulin** [comment]
This change has been integrated and will be in the next release (v1.00)

**Comment by jspelletier** [comment]
thanks

**Pull request merged**
