### PR TITLE
implements Ctrl-C on linux

### PR DESCRIPTION
**Pull request by comicfans**
may also works for OSX, but I didn't have one to test. so I leave this code predefined for linux only

### CODE REVIEW

**Comment by Leandros** [comment]
That is technically undefined behaviour. While it may work, the only legal thing you're allowed to do in a signal handler is setting a `volatile sig_atomic_t`.

**Comment by comicfans** [comment]
Hmm, I should read your references first ...

**Comment by ffulin** [comment]
I think forking a process in order to be strictly compliant is going to be unworkable (since we'd have to pass all the state across processes anyway).
I think even if it's not strictly per the C++ standards, it's worth handling the Ctrl+C as in the pull request, because it'll almost certain work just fine, and even if it doesn't, then in the absolute worst case we're no worse off than the current behaviour.

**Comment by ffulin** [comment]
I've integrated this into the Perforce mainline. This will be in the next release (v0.94). Thanks for the pull request.

**Pull request merged**
